version: "3"

services:
    redis:
        image: redis:alpine
        volumes:
            - redis-data:/data

    celeryd:
        build:
            dockerfile: ./app.dockerfile
            context: .
        command: celery worker --app=app --workdir=/code --events --loglevel=debug
        environment:
            - C_FORCE_ROOT=1
        depends_on:
            - redis
        volumes:
            - .:/code
  
    celery-logger:
        build:
            dockerfile: celerylogger/Dockerfile
            context: ../
        command: python celery_logger.py --celery-broker=redis://redis:6379/0
        links:
            - redis
            
volumes:
    redis-data:
